AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy External DNS controller into the "Amazon EKS QuickStart"
  uses IRSA (IAM Role for Service Account)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: ExternalDNS
        Parameters:
          - domainFilters
          - externalDNSOption
      - Label:
          default: Kube Cluster
        Parameters:
          - KubeClusterName
          - KubeConfigPath
          - KubeGetLambdaArn
          - KubeConfigKmsContext
          - KubeOIDCProvider          
          - HelmLambdaArn
          - Namespace
          - Name
          - RepoUrl
          
    ParameterLabels:
      domainFilters:
        default: Domain to filter with external DNS
      externalDNSOption:
        default : ExternalDNS option policy
      KubeOIDCProvider:
        default: Name of the oidc provider associate with your EKS Cluster
      KubeClusterName:
        default: EKS Kube Cluster Name
      KubeConfigPath:
        default: Kube Config Path
      KubeGetLambdaArn:
        default: Kube Get Lambda ARN
      KubeConfigKmsContext:
        default: Kube KMS Context
      HelmLambdaArn:
        default: EKS Stack HelmLambda ARN
      Namespace:
        default: Kube Namespace for this function
      Name:
        default: Kube Name for this function
      RepoUrl:
        degault: Helm repo to uses
        
Parameters:
   domainFilters:
     Description: 'ex: sub.mydomain.com'
     Type: String
   externalDNSOption:
     Description: '(options: sync, upsert-only)'
     Type: String
     Default: "sync"
   KubeOIDCProvider:
    Description: 'Get the oidc provider from your EKS configuration without https: ex: oidc.eks.us-east-1.amazonaws.com/id/17B548BB618492173CE72DB7BF83E921'
    Type: String
   HelmLambdaArn:
    Description: 'Get this from the EKSStack outputs section in CloudFormation.'
    Type: String
   KubeClusterName:
    Description: 'Get this from the EKSStack outputs section in CloudFormation.'
    Type: String
   KubeConfigPath:
    Description: 'Get this from the EKSStack outputs section in CloudFormation.'
    Type: String
   KubeConfigKmsContext:
    Description: 'This is using the default from the AWS EKS Quick Start, if you modified
    this context when deploying. You need to use the modified KMS context here.'
    Type: String
    Default: "EKSQuickStart"
   Namespace:
    Description: 'Modify to use a custom Namespace. The Namespace up to 63 characters
    long. The characters allowed in names are: digits (0-9), lower case letters (a-z),
    and underscore(s)(cannot start or end with)'
    Type: String
    Default: "kube-system"
   Name:
    Description: 'Modify to use a custom Names. The Names up to 253 characters
    long. The characters allowed in names are: digits (0-9), lower case letters (a-z), -,
    and ..'
    Type: String
    Default: "external-dns"
   RepoUrl:
    Description: 'Modify to use a other helm repo than stable'
    Type: String
    Default: "https://kubernetes-charts.storage.googleapis.com"
    
Resources:

  ExternalDNSPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'route53:ChangeResourceRecordSets'
            Resource:
              - 'arn:aws:route53:::hostedzone/*'
          - Effect: Allow
            Action:
              - 'route53:ListHostedZones'
              - 'route53:ListResourceRecordSets'
            Resource:
              - '*'

  ExternalDNSRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${KubeOIDCProvider}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "${KubeOIDCProvider}:aud": "sts.amazonaws.com",
                    "${KubeOIDCProvider}:sub": "system:serviceaccount:kube-system:${Name}"
                  }
                }
              }
            ]
          }
      ManagedPolicyArns:
        - !Ref ExternalDNSPolicy

  ExternalDNSHelmChart:
    Type: "Custom::Helm"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref HelmLambdaArn
      KubeConfigPath: !Ref KubeConfigPath
      KubeConfigKmsContext: !Ref KubeConfigKmsContext
      KubeClusterName: !Ref KubeClusterName
      Namespace: !Ref Namespace
      Chart: stable/external-dns
      Name: !Ref Name
      RepoUrl: !Ref RepoUrl
      Values:
        clusterName: !Ref KubeClusterName
        domainFilters[0]: !Ref domainFilters
        rbac.serviceAccountAnnotations."eks\.amazonaws\.com/role-arn": !GetAtt ExternalDNSRole.Arn
        txt-owner-id: !Ref KubeClusterName
        policy: !Ref externalDNSOption

Outputs:
  ExternalDNSReleaseName:
    Value: !Ref ExternalDNSHelmChart

